-- Extend stock_market_data with OpenD get_market_snapshot fields
ALTER TABLE stock_market_data
    ADD COLUMN IF NOT EXISTS avg_price              DECIMAL(20, 8) NULL AFTER ask_price,
    ADD COLUMN IF NOT EXISTS amplitude              DECIMAL(20, 8) NULL AFTER avg_price,
    ADD COLUMN IF NOT EXISTS volume_ratio           DECIMAL(20, 8) NULL AFTER amplitude,
    ADD COLUMN IF NOT EXISTS bid_ask_ratio          DECIMAL(20, 8) NULL AFTER volume_ratio,
    ADD COLUMN IF NOT EXISTS bid_vol                DECIMAL(20, 4) NULL AFTER bid_ask_ratio,
    ADD COLUMN IF NOT EXISTS ask_vol                DECIMAL(20, 4) NULL AFTER bid_vol,
    ADD COLUMN IF NOT EXISTS pe_ratio               DECIMAL(20, 8) NULL AFTER ask_vol,
    ADD COLUMN IF NOT EXISTS pe_ttm_ratio           DECIMAL(20, 8) NULL AFTER pe_ratio,
    ADD COLUMN IF NOT EXISTS pb_ratio               DECIMAL(20, 8) NULL AFTER pe_ttm_ratio,
    ADD COLUMN IF NOT EXISTS total_market_val       DECIMAL(24, 4) NULL AFTER pb_ratio,
    ADD COLUMN IF NOT EXISTS circular_market_val    DECIMAL(24, 4) NULL AFTER total_market_val,
    ADD COLUMN IF NOT EXISTS issued_shares          DECIMAL(24, 0) NULL AFTER circular_market_val,
    ADD COLUMN IF NOT EXISTS outstanding_shares     DECIMAL(24, 0) NULL AFTER issued_shares,
    ADD COLUMN IF NOT EXISTS turnover_rate          DECIMAL(20, 8) NULL AFTER outstanding_shares,
    ADD COLUMN IF NOT EXISTS lot_size               INT NULL AFTER turnover_rate,
    ADD COLUMN IF NOT EXISTS highest52weeks_price   DECIMAL(20, 8) NULL AFTER lot_size,
    ADD COLUMN IF NOT EXISTS lowest52weeks_price    DECIMAL(20, 8) NULL AFTER highest52weeks_price,
    ADD COLUMN IF NOT EXISTS highest_history_price  DECIMAL(20, 8) NULL AFTER lowest52weeks_price,
    ADD COLUMN IF NOT EXISTS lowest_history_price   DECIMAL(20, 8) NULL AFTER highest_history_price,
    ADD COLUMN IF NOT EXISTS dividend_ttm           DECIMAL(20, 8) NULL AFTER lowest_history_price,
    ADD COLUMN IF NOT EXISTS dividend_ratio_ttm     DECIMAL(20, 8) NULL AFTER dividend_ttm,
    ADD COLUMN IF NOT EXISTS dividend_lfy           DECIMAL(20, 8) NULL AFTER dividend_ratio_ttm,
    ADD COLUMN IF NOT EXISTS dividend_lfy_ratio     DECIMAL(20, 8) NULL AFTER dividend_lfy,
    ADD COLUMN IF NOT EXISTS earning_per_share      DECIMAL(20, 8) NULL AFTER dividend_lfy_ratio,
    ADD COLUMN IF NOT EXISTS net_asset_per_share    DECIMAL(20, 8) NULL AFTER earning_per_share,
    ADD COLUMN IF NOT EXISTS listing_date           DATE NULL AFTER net_asset_per_share,
    ADD COLUMN IF NOT EXISTS sec_status             VARCHAR(32) NULL AFTER listing_date,
    ADD COLUMN IF NOT EXISTS suspension             TINYINT(1) NULL AFTER sec_status;
