-- Apply on existing MariaDB (docker exec / SQLyog)
CREATE TABLE IF NOT EXISTS stock_market_data (
    id              BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code            VARCHAR(64) NOT NULL,
    name            VARCHAR(255) NULL,
    market          VARCHAR(16) NULL COMMENT 'HK / US / CN / ...',
    product_type    VARCHAR(32) NOT NULL DEFAULT 'STOCK',
    last_price      DECIMAL(20, 8) NULL,
    open_price      DECIMAL(20, 8) NULL,
    high_price      DECIMAL(20, 8) NULL,
    low_price       DECIMAL(20, 8) NULL,
    prev_close      DECIMAL(20, 8) NULL,
    change_val      DECIMAL(20, 8) NULL,
    change_pct      DECIMAL(20, 8) NULL,
    volume          DECIMAL(20, 4) NULL,
    turnover        DECIMAL(20, 4) NULL,
    bid_price       DECIMAL(20, 8) NULL,
    ask_price       DECIMAL(20, 8) NULL,
    currency        VARCHAR(8) NULL,
    quote_time      DATETIME(6) NULL,
    is_favourite    TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 = my favourite',
    remark          VARCHAR(255) NULL,
    source          VARCHAR(32) NOT NULL DEFAULT 'opend',
    created_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_stock_market_data_code (code),
    KEY idx_stock_market_data_favourite (is_favourite),
    KEY idx_stock_market_data_market (market)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
