-- Option contract snapshots (ATM ± N strike steps)
CREATE TABLE IF NOT EXISTS option_market_data (
    id                   BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code                 VARCHAR(64) NOT NULL COMMENT 'Option contract code e.g. HK.TCH261029C420000',
    name                 VARCHAR(255) NULL,
    underlying           VARCHAR(64) NOT NULL COMMENT 'Owner stock/index e.g. HK.00700',
    underlying_price     DECIMAL(20, 8) NULL,
    option_type          VARCHAR(8) NOT NULL COMMENT 'CALL / PUT',
    strike_price         DECIMAL(20, 8) NOT NULL,
    expiry               DATE NOT NULL,
    expiration_cycle     VARCHAR(16) NULL COMMENT 'WEEK / MONTH / ...',
    strike_offset        INT NULL COMMENT 'Strike steps from ATM: -4..+4',
    last_price           DECIMAL(20, 8) NULL,
    bid_price            DECIMAL(20, 8) NULL,
    ask_price            DECIMAL(20, 8) NULL,
    mid_price            DECIMAL(20, 8) NULL,
    prev_close           DECIMAL(20, 8) NULL,
    change_val           DECIMAL(20, 8) NULL,
    change_pct           DECIMAL(20, 8) NULL,
    volume               DECIMAL(20, 4) NULL,
    turnover             DECIMAL(20, 4) NULL,
    open_interest        DECIMAL(20, 4) NULL,
    iv                   DECIMAL(20, 8) NULL COMMENT 'Implied volatility %%',
    delta                DECIMAL(20, 8) NULL,
    gamma                DECIMAL(20, 8) NULL,
    vega                 DECIMAL(20, 8) NULL,
    theta                DECIMAL(20, 8) NULL,
    rho                  DECIMAL(20, 8) NULL,
    premium              DECIMAL(20, 8) NULL,
    lot_size             INT NULL,
    contract_size        DECIMAL(20, 4) NULL,
    expiry_days          INT NULL,
    suspension           TINYINT(1) NULL,
    quote_time           DATETIME(6) NULL,
    source               VARCHAR(32) NOT NULL DEFAULT 'opend',
    created_at           DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at           DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_option_market_data_code (code),
    KEY idx_option_market_underlying_expiry (underlying, expiry),
    KEY idx_option_market_expiry (expiry)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
